### DISCUSSION TITLE
6.4.2 381p~382p 프론트엔드 배포가 되질 않습니다..

### DISCUSSION THREAD

**Discussion by daseul-jang** [fsoftwareengineer/todo-application#113] [질문과 답변]
백엔드까지는 ok 상태로 됐는데 프론트는 계속 severe 상태입니다..

에러 캡처입니다. 
![image](https://user-images.githubusercontent.com/77530419/164528193-c50d67e1-7751-41fc-8387-6b833badcada.png)

환경 상태 캡처입니다.
![image](https://user-images.githubusercontent.com/77530419/164530160-a3a6485a-f19c-40ce-a488-4ed5a62efd93.png)

에러로그 첨부합니다.
[에러로그.txt](https://github.com/fsoftwareengineer/todo-application/files/8534125/default.txt)

에러로그를 보면 web.stdout.log 부분에
Apr 21 15:49:42 ip-172-31-11-142 web: > react-todo-app@0.1.0 start
Apr 21 15:49:42 ip-172-31-11-142 web: > react-scripts start
Apr 21 15:49:42 ip-172-31-11-142 web: sh: /var/app/current/node_modules/.bin/react-scripts: Permission denied

이런 에러로그가 반복해서 뜨길래
https://github.com/fsoftwareengineer/todo-application/discussions/35#discussioncomment-1888637
위의 방법을 참고해서 따라해보았으나 전혀 고쳐지지 않고 같은 에러가 반복됩니다 ㅠㅠ

아래는 에러를 고치기 위해 시도한 방법들 입니다.

![image](https://user-images.githubusercontent.com/77530419/164531247-f722ecef-b3e1-465e-b54b-28c6119c0ac3.png)

1. 루트 디렉토리에 .ebignore 파일 생성
```
.git
.gitignore
```

2. 루트 디렉토리에 .npmrc 파일 생성
```
unsafe-perm=true
engine-strict=true
```

3. 루트 디렉토리에 .ebextensions 폴더 생성 후 01-permissions.config 파일 생성
(01-permissions.config, 01-permissions.config.yaml 둘 다 시도해봄)
```
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/pre/49_change_permissions.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/usr/bin/env bash
      sudo chown -R ec2-user:ec2-user tmp/
```

에러 해결해보겠다고 뭐 하나 추가하면 다른 에러 (ex npm install 에러, web.pid 파일을 찾을 수 없다는 에러.. 등등)가 터져서 이것저것 시도해봤습니다만 다 실패했습니다.. ㅠㅠ

다른 프로젝트는 어떨까 싶어서 create-react-app으로 생성한 프로젝트를 아무것도 건드리지 않고 깃 커밋만 하여 배포해봤으나 역시나 위와 같은 에러들(react-scripts: Permission 등)만 반복되며 배포가 되질 않았습니다..

마지막으로 .elasticbeanstalk/config.yml 파일과 전체 소스코드가 있는 깃허브 주소 남깁니다.
```
branch-defaults:
  main:
    environment: TodoApplication-frontend-dev
    group_suffix: null
global:
  application_name: TodoApplication-frontend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
```

https://github.com/daseul-jang/react-todo-app_front
