### DISCUSSION TITLE
p.367 실습코드 6-12 진행후 상태 Ok로 바뀌지않을때

### DISCUSSION THREAD

**Discussion by Onthesly** [fsoftwareengineer/todo-application#32] [자신의 진행 상황 공유]
[실습코드 6-12]
eb setenv SPRING_PROFILES_ACTIVE=prod 
수행후에도 저와 같이 Elastic Beanstalk 상태가 Ok로 변하지 않고 
URL 클릭시 502 에러가 발생하는 분들이 계실까봐 적습니다.
(제가 IDE를 STS4(eclipse)를 써서 저만 발생한 경우일수도 있습니다!!
application-properties.yml이 아닌 application.properties파일이 있었습니다.)

![image](https://user-images.githubusercontent.com/87744184/146317004-1b6e0c1d-09b6-474c-861f-c52e0bd05b88.png)
p366 6.3.5를 따라 그림과 같이 만들경우 application-prod.yaml을 자동인식하지 못하는것 같습니다.
그래서 구글링하여 application.yaml하나에 profiles로 dev와 prod 구분하였습니다.
```
spring:
  profiles: dev
  
---

spring:
  profiles: prod
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password} 
server:
  port: 5000
```
application.yaml

간단한 해결방법이지만 저의 경우는 properties 부분을 처음 건드려봐서 해결하는데 오랜 시간이 걸렸습니다.
저와 같은 오류가 발생하신분들에게 도움이 될까 작성합니다.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

profiles만 쓰는것이 스프링부트 2.4.0부터 deprecated라고 해서 다른방법도 적습니다.
application.yaml , application-dev.yaml, application-prod.yaml을 만든 후
applicaiton-prod.yaml은 실습코드 6-6과 동일하게 작성하고

![image](https://user-images.githubusercontent.com/87744184/146321370-c8b655c3-bef3-4506-926a-595c6cad0d99.png)

```
spring:
  profiles:
    activate:
      on-profile: dev
  
---

spring:
  profiles:
    activate:
     on-profile: prod
```
application.yaml 에 코드를 작성해도 Ok됩니다.
제가 잘못 이해하고 있는 부분 있으면 언제나 comment 부탁드립니다!
